### ISSUE TITLE
Feature Request: Make separate library to set raw mode

### ISSUE THREAD

**Issue by legolord208** [ticki/termion#112]
Hello! I am interested in setting the terminal to raw mode, and I don't really want any other features this library offers. Is there any chance you could split or copy the raw part into a separate library?

Cheers!

**Comment by ticki** [comment]
why

**Comment by legolord208** [comment]
> I am interested in setting the terminal to raw mode, and I don't really want any other features this library offers

**Comment by gyscos** [comment]
Termion doesn't have a lot of dependencies, so it's not a big cost to depend on it even if you only use a few things - it won't bloat the final binary.
If you _really_ want to include only the minimal amount of code - which is a rare use-case - you'll have to copy the code from [raw.rs](https://github.com/ticki/termion/blob/master/src/raw.rs) to your project.

**Comment by legolord208** [comment]
Currently my project is doing ANSI escape codes manually. And that's fine, because it's only supposed to work on rich terminals, and it makes me know how much to allocate.

Anyways, importing this would make me feel weird for not using most of it's features. But I guess it's just a personal thing, since Rust probably optimizes away unused functions either way.

Yeah, guess you're right. Sorry for bothering you :)

**Comment by ticki** [comment]
Yeah, since it is a static library, you will only end up using the few functions, you use.
