### ISSUE TITLE
Maybe a missing `extern crate sys;`

### ISSUE THREAD

**Issue by TimonPost** [ticki/termion#121]
When I build the code whit cargo I get the following errors: 
![image](https://user-images.githubusercontent.com/19969910/29753723-db3443c0-8b77-11e7-8acd-f530ec88681e.png)

**details:**
Terminal: windows terminal, git bash terminal.
version: termion v1.5.1

**code that I tried to execute:**

```
extern crate termion;
fn main()
{
    print!("{}{}Stuff", termion::clear::All, termion::cursor::Goto(1, 1));
}
````

**cargo.toml**
```
[dependencies]
termion = "1.0.0"
```

**Comment by gyscos** [comment]
Are you running this on Windows? It is not currently a supported platform.

**Comment by TimonPost** [comment]
Yes I am, I tried to run it on windows terminal
