### ISSUE TITLE
Make `Key` a clone type

### ISSUE THREAD

**Issue by MovingtoMars** [ticki/termion#24]
This would be helpful, especially considering `Key` is a relatively small type.

**Comment by ticki** [comment]
Unfortunately this is not possible due to `io::Error`'s lack of `clone`.

**Comment by MovingtoMars** [comment]
Have you considered taking the `Error` variant out of `Key`, and just iterating over `io::Result<Key>`?

**Comment by ticki** [comment]
That's a good idea, actually.
