### ISSUE TITLE
Seeing libc errors with sample

### ISSUE THREAD

**Issue by jonathandturner** [ticki/termion#35]
When I try to compile your first example, I see:

```
error[E0432]: unresolved import `libc::termios`. There is no `termios` in `libc`
 --> C:\Users\jont\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.0.0\src\termios.rs:4:9
  |
4 | pub use libc::termios as Termios;
  |         ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0432]: unresolved import `libc::ioctl`. There is no `ioctl` in `libc`
  --> C:\Users\jont\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.0.0\src\size.rs:33:9
   |
33 |     use libc::ioctl;
   |         ^^^^^^^^^^^
...
```

Is there something I need to do to get libc also compiling?  I'm trying to build this on Windows, if that also has an impact.

**Comment by ticki** [comment]
Unfortunately, it doesn't work on Windows, due to the odd term API.

**Comment by jonathandturner** [comment]
Ah, I missed the "Supports Redox, Mac OS X, BSD, and Linux (or, in general, ANSI terminals)."

Hopefully you'll be able to add support for Windows also.  I've been looking for a simple terminal crate.

**Comment by ticki** [comment]
> Hopefully you'll be able to add support for Windows also. I've been looking for a simple terminal crate.

I have no Windows machine available for testing, but having Windows support would be very nice. If somebody makes a PR, I'll certainly merge it.

**Comment by jonathandturner** [comment]
I may look into it.  There's already other term crates, too.  Would be great if they could merge support/feature set...
