### ISSUE TITLE
No way to store arbitrary colors

### ISSUE THREAD

**Issue by gyscos** [ticki/termion#53]
Hi,

I cannot find a way to store an arbitrary color in a struct and use it in a `Fg` or `Bg`. Possible solutions:
- Have an `enum` implementing `Color` with a variant for each color type.
- Store a `Box<Color>` as a trait object. The easiest way for that is probably to have `impl <C: Color> Color for Box<C>`.

The first option is more efficient (no heap allocation required), while the second option is more extensible if users define their own types implementing `Color`. These two options are also not incompatible.

**Comment by ticki** [comment]
I had `Palette` at one point, which did exactly this.

**Comment by gyscos** [comment]
Just noticed I could actually declare `struct ColorRef<'a>(&'a Color);` and implement `Color` for it, without requiring to add anything to termion itself. A `Palette` still sounds like a better solution overall, but at least there's a workaround for now.

**Comment by ticki** [comment]
I've fixed this by impling `Color` for the trait object, so there is no need for `ColorRef`.

I don't think `Palette` is a good idea, because it likely has more overhead as there is at least 5 branches involved.
