### ISSUE TITLE
read_passwd no longer works

### ISSUE THREAD

**Issue by jackpot51** [ticki/termion#74]
Read password is now echoing password bytes. This can be seen in the login prompt on Redox

**Comment by jackpot51** [comment]
This may be an issue with `ransid` or `vesad` as well, I will close if it is

**Comment by jackpot51** [comment]
This appears to happen in release mode because the compiler optimizes out the .into_raw_mode()

**Comment by ticki** [comment]
> This appears to happen in release mode because the compiler optimizes out the .into_raw_mode()

That sounds really bad. UB somewhere?

**Comment by jackpot51** [comment]
You need to use the handle you get back somehow

**Comment by jackpot51** [comment]
Even just a flush would work

**Comment by ticki** [comment]
Closing as wontfix, because it is likely due to the lack of flushing rather than an actual bug.
