### ISSUE TITLE
unicode seems to hang up

### ISSUE THREAD

**Issue by spacejam** [ticki/termion#75]
https://github.com/spacejam/void/issues/6
reproduced on urxvt & xterm on linux 4.8.10 with german keyboard `setxkbmap de`

**Comment by iqualfragile** [comment]
also works on the suckless st

**Comment by iqualfragile** [comment]
not limited to umlauts, also greek letters(ελτ) and other non-ascii-symbols(✔✔).
maybe something about the bytes? ascii is one byte the others are more then that.

**Comment by gyscos** [comment]
Seems to be caused by `input.rs:62` keeping some continuation bytes as leftover, even though they're consumed by `parse_event()`.

**Comment by gyscos** [comment]
Should be fixed now.

**Comment by ticki** [comment]
Yup.

**Comment by spacejam** [comment]
Thanks folks!
