### ISSUE TITLE
Support for the alternate screen

### ISSUE THREAD

**Issue by FreeFull** [ticki/termion#77]
When a curses program starts, curses switches the screen to the "alternate screen" using the `smcup` terminfo capability, and then switches back using `rmcup` on exit. It'd be nice to have support for this in termion as well.

**Comment by ticki** [comment]
This is somewhat similar to what `TerminalRestorer` in Termion does, except that it doesn't restore the textual state. I suppose it should.

**Comment by IGI-111** [comment]
If I may, this is basically what #66 did.

If not by default, it probably should be available in some form.

**Comment by jackpot51** [comment]
@IGI-111 This must, must, must be implemented in a way that wraps RawTerminal, instead of forcing this into RawTerminal, because it would break line editors otherwise. I would recommend AlternateScreen<T: Read> that switches to the alternate screen on AlternateScreen::new and switches back on drop.

**Comment by joshhansen** [comment]
Just discovered this and wanted to say it seems to be working properly for me using the 1.3.0 release. Thanks for implementing.

**Comment by ticki** [comment]
Yep. I'm going to close this issue for now.
