### ISSUE TITLE
stdin.read_passwd: Ability to fall back into normal mode if raw mode fails

### ISSUE THREAD

**Issue by untitaker** [Ticki/termion#8]
I want to pipe a password into my program (which uses `TermRead.read_passwd`), but I can't do this because termion insists on entering raw mode.

Python's `getpass` will print a warning if raw mode couldn't be entered: https://docs.python.org/3/library/getpass.html#module-getpass.

TBH, I can't imagine a usecase where I want to prevent users from entering a password just because e.g. the tty is borked, on the other hand I can understand if you don't want to silently ignore errors.

**Comment by Ticki** [comment]
It returns a `Err` when it is unable to enter raw mode.

**Comment by untitaker** [comment]
Yes, the point is that I'd like it to continue reading stdin even though raw mode failed.

On 16 March 2016 07:50:32 CET, Ticki <notifications@github.com> wrote:
>It returns a `Err` when it is unable to enter raw mode.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Ticki/termion/issues/8#issuecomment-197183521

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Ticki** [comment]
Well, that can be handled by the caller to give more fine-grained control.

**Comment by untitaker** [comment]
It can't if I want to use `TermRead::read_passwd` and not reimplement its logic (particularly the for-loop).

**Comment by untitaker** [comment]
@Ticki Should I open a PR to show what I mean, or are you opposed in principle?

If backwards compat is a concern, I could also add a method called `try_read_password`, which is equivalent to `read_passwd` except it doesn't abort if raw mode can't be entered.

**Comment by Ticki** [comment]
Well, I don't disagree in principle, I am just unsure if it fits this library. Feel free to open a PR, though!

**Comment by untitaker** [comment]
I've submitted https://github.com/Ticki/termion/pull/14 which is, I think, a bit less controversial: Factoring out `read_line` into its own function allows me to trivially implement the behavior I want with a two-line function in my own code.

The only thing I'm unsure about is the name of `read_line`, as it conflicts with https://doc.rust-lang.org/std/io/trait.BufRead.html#method.read_line. Is there a reason the logic of `BufRead`'s method isn't used?

**Comment by untitaker** [comment]
see #14
