### ISSUE TITLE
User-perceived character alignment

### ISSUE THREAD

**Issue by jtomschroeder** [ticki/termion#83]
When writing characters of multiple codepoints (e.g. ❤), text does not appear aligned.

![screen shot 2016-12-21 at 2 22 23 pm](https://cloud.githubusercontent.com/assets/1320768/21404895/f68ab0fe-c788-11e6-896e-2559e78042ad.png)

**Comment by ticki** [comment]
This has to do with your terminal emulator and not Termion, as Termion doesn't render but only outputs escape codes.

**Comment by gyscos** [comment]
Note: the problem is that the character `❤` is define as single-width, but still has a glyph larger than a single column.
It's actually a [problem with unicode itself](http://unicode.org/reports/tr11/#ED7).
